### ISSUE TITLE
Submit an Event - Thank you message is appearing in green box - see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#103]
<img width="748" alt="screen shot 2017-08-08 at 9 05 47 am" src="https://user-images.githubusercontent.com/8631079/29090678-4ed81998-7c4e-11e7-92f3-aa7823df6163.png">

**Comment by ccmorris** [comment]
"Thank you message is appearing in green box"

I agree, it is. What do you want?

**Comment by tgascoigne14** [comment]
It should look like the other thank you message pages and less like a possible issue. Users should not see "submitted email, with ID ......" and only see the thank you message with a white background and not in a box.

![screen shot 2017-08-09 at 4 57 57 pm](https://user-images.githubusercontent.com/8631079/29143677-f39d73d0-7d23-11e7-9f57-83eedb3467bb.png)
