### ISSUE TITLE
Contact Form Submission - Users should not see the "Submitted email, with ID ...." wording or green box

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#104]
![screen shot 2017-08-09 at 4 58 01 pm](https://user-images.githubusercontent.com/8631079/29143785-6403fa86-7d24-11e7-9df0-73da65bd428a.png)

**Comment by ccmorris** [comment]
You won't see this message when we disable the email rerouting for testing.

It is routing ALL email to Sue so that there are no unintentional messages sent to actual members right now.
