### ISSUE TITLE
Event Calendar - Next Month and Previous Month buttons not working as expected

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#12]
I clicked 'Next Month' when I was in the May calendar, it brought me to July. I clicked next again and it brought me to August. I clicked again and it brought me to October.

**Comment by ccmorris** [comment]
I believe this issue only exists when the current day is the 31st day of the month. This will be kinda difficult to test tomorrow, but if the problem disappears tomorrow then that is a clue.

More info and d.org issue: https://www.drupal.org/node/2737239

**Comment by tgascoigne14** [comment]
I just went to the calendar to test if this was still an issue - the calendar still says its May 31 and when I clicked next month it goes to July.

**Comment by ccmorris** [comment]
I saw what you described. Then I cleared the Drupal cache and it was resolved.
I think there are also issues with caching this page. Obviously the server should not cache page into the next day.
