### ISSUE TITLE
Library Article - Breadcrumb is missing a link to its parent: Library

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#16]
![screen shot 2017-05-31 at 11 11 00 am](https://cloud.githubusercontent.com/assets/8631079/26639092/e41d5df8-45f1-11e7-8557-be90866cf4d9.png)

**Comment by tgascoigne14** [comment]
Still missing

**Comment by ccmorris** [comment]
I just needed to regenerate the URL aliases for the content on staging.
