### ISSUE TITLE
Safari - Events Calendar - Calendar is much larger than other browsers - see screenshots

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#17]
Chrome

![screen shot 2017-05-31 at 11 34 31 am](https://cloud.githubusercontent.com/assets/8631079/26641494/ccb82132-45f8-11e7-8ad1-ca70e20b1dcf.png)

Safari
![screen shot 2017-05-31 at 11 34 49 am](https://cloud.githubusercontent.com/assets/8631079/26641501/d08b5644-45f8-11e7-9621-21b465e61527.png)

**Comment by ccmorris** [comment]
Can you tell me which version of Safari you are using?

I don't see this issue on Safari on my computer.

**Comment by tgascoigne14** [comment]
Version 9.1.2 (10601.7.7)

**Comment by ccmorris** [comment]
This is obviously a browser compatibility issue. Safari 9 ended support from Apple last year. Nobody should be using it. Yourself included btw, there are many security updates since then.

I'm not sure we should be supporting it.

**Comment by ccmorris** [comment]
I did manage to find the issue for Safari <= 9 and it was easy to fix.
