### ISSUE TITLE
Members Area - Document and Notices - Adding a document - Error message when uploading a file

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#18]
![screen shot 2017-05-31 at 12 26 36 pm](https://cloud.githubusercontent.com/assets/8631079/26642627/73b06366-45fc-11e7-8b81-62b436b0fab7.png)

**Comment by ccmorris** [comment]
I think you have specify which file types are allowed. You cannot choose to upload ANY file type you want. I will look into this a little more.

**Comment by tgascoigne14** [comment]
I tried to upload a pdf, word doc, xls, and pptx and the same error message came up

**Comment by ccmorris** [comment]
Oh. I thought you meant that you tried to upload something that it says it not allowed. But you're saying you uploaded an allowed file type and it failed. I see that error message has absolutely nothing to do with file types. I will rewrite this issue.

**Comment by ccmorris** [comment]
Fixed in config. The "private" filesystem was not configured on this environment yet, and that's what caused these member notice errors.
