### ISSUE TITLE
Members Area - Document and Notices - Did not add a document and pressed save - see screenshot for error messages

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#19]
![screen shot 2017-05-31 at 12 27 35 pm](https://cloud.githubusercontent.com/assets/8631079/26642670/9e5d3472-45fc-11e7-8532-3fe1f1ee1a76.png)

**Comment by ccmorris** [comment]
Fixed in config. The "private" filesystem was not configured on this environment yet, and that's what caused these member notice errors.
