### ISSUE TITLE
Members Area - Document and Notices - When logged in as admin, I cannot see the documents and notices that were added.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#20]
You can see them when logged in as a member

**Comment by ccmorris** [comment]
They are meant for members. Is this wrong?

The admin can see all content in the admin area.

**Comment by tgascoigne14** [comment]
This is correct, they are meant for members. I just know they will like to see the list of docs/notices in the actual members area opposed to just the admin area.
