### ISSUE TITLE
Documents and Notices - I tried to access and edit 'ODEN Document 1' and this error page came up - 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#21]
![screen shot 2017-05-31 at 12 30 16 pm](https://cloud.githubusercontent.com/assets/8631079/26642782/0e8449a2-45fd-11e7-9175-83d1eff38efe.png)

**Comment by ccmorris** [comment]
Fixed in config. The "private" filesystem was not configured on this environment yet, and that's what caused these member notice errors.
