### ISSUE TITLE
Library Categories - iPhone & iPad Portrait view - Search bar overlaps onto library category boxes

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#24]
![img_4753](https://cloud.githubusercontent.com/assets/8631079/26653279/a4423a44-4620-11e7-8555-e10de09bf6a0.png)

**Comment by tgascoigne14** [comment]
![img_4754](https://cloud.githubusercontent.com/assets/8631079/26653547/6b72eb2c-4621-11e7-9ed1-af1320b8473a.png)

**Comment by ccmorris** [comment]
dupe of #25
