### ISSUE TITLE
iPad- Stripe payment - does not show the price members will be paying

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#26]

**Comment by ccmorris** [comment]
is this specific to iPads?

**Comment by tgascoigne14** [comment]
I can see it when using my phone and it works on desktop as well. When on the iPad -it- just has the regular fields and the pay button, there is no price.

**Comment by ccmorris** [comment]
It looks exactly the same to me on tablet, phone, and desktop. You will have to show me what you are seeing.

It is also using a new tab for the credit card input, only because the page is not served with https. You obviously shouldn't be collecting credit card numbers without https.

**Comment by ccmorris** [comment]
Tina showed me the bug. I will have to do some research.

**Comment by ccmorris** [comment]
@tgascoigne14 
What do you think about adding another field at the bottom of the registration form that shows the user their total price?

**Comment by tgascoigne14** [comment]
@ccmorris I think this is a good solution.

**Comment by ianfader** [comment]
Price does not show in IE 11

**Comment by ianfader** [comment]
Price is showing as $NaN on iPad. Is fine on desktop and mobile
