### ISSUE TITLE
Library Search - Search has "no results" even when searching the name of the article

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/ODEN#36]
I searched for the article "We Connect Now" in the Education category using the search library search bar and got no results.

**Comment by ccmorris** [comment]
Is this still an issue? I saw it was definitely an issue when you showed it to me. But nowI can see results. I suspect that the content just needed to be indexed (by cron), and it is now indexed.

**Comment by ianfader** [comment]
Can confirm that the search library search field is now showing results.
