### ISSUE TITLE
Contact Us - Form - Required fields

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/ODEN#38]
@tgascoigne14 We have "preferred method of communication" as a required field but the user doesn't have to actually fill out the phone or email fields. Also, should "reason for communication" be required?

**Comment by ccmorris** [comment]
or less fields

**Comment by tgascoigne14** [comment]
@ccmorris It is stated in the scoping document that name, phone number, email address, and message are required. I missed this during testing. The reason for communication field is fine as is. Currently, the email field is set up so users cannot submit the form without an @ in the email address. Phone number is fine
