### ISSUE TITLE
Create New Account - Help user fill out address field by adding in city field

### ISSUE THREAD

**Issue by ianfader** [CCI-Studios/ODEN#41]
This is what happens when the user submits just an address:

![screen shot 2017-06-02 at 11 52 41 am](https://cloud.githubusercontent.com/assets/8989188/26733818/03a1f55a-478a-11e7-9093-26e519c80d2f.png)

**Comment by ccmorris** [comment]
or help text

**Comment by ccmorris** [comment]
added help text in the user registration form and edit user form to remind the user to include the city and province so that the pin on the member map is accurate.
