### ISSUE TITLE
Adding Images - There is no way to resize the images when being added to the site

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#7]

**Comment by ccmorris** [comment]
Yes there is. In the file browser, select the image file, click Resize.

**Comment by tgascoigne14** [comment]
This feature is not working for me. I replaced a photo (Shawn Callaghan) in the Business Champions League section because I was unable to format the image that was there. The original size is 638x638 and I resized it to 350x350, added it to the page and the image did not resize.

**Comment by ccmorris** [comment]
The image there is 350x350. What is not working?

**Comment by ccmorris** [comment]
browser cached the image
