### ISSUE TITLE
Events - List View - Event time is missing

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#73]
![screen shot 2017-06-15 at 3 12 57 pm](https://user-images.githubusercontent.com/8631079/27197683-341fede2-51dd-11e7-8b1f-cae47e5d43d0.png)

Also, formatting of the date, time, and ODEN logo are off

**Comment by ccmorris** [comment]
Ah yes, the date and time were once one field, then we split to a separate field to simplify the date range field. Then the event time was forgotten here.
