### ISSUE TITLE
Adding Images - There is no way to add spacing between image and text

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#8]

**Comment by ccmorris** [comment]
I honestly don't know how to get that functionality back in Drupal 8. My searching has been futile. I can do it manually in the content source code.

I will probably revisit this. I am annoyed.

**Comment by ccmorris** [comment]
I added some margins automatically when you align things.

eg. if you align an image to left, then a margin is automatically added to the right of the image.
