### ISSUE TITLE
Become a Member - Text area before form - please add the following text under the first sentence.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/ODEN#83]
All new members are required to complete the form below.  Each member organization will be given one username and password.

**Comment by tgascoigne14** [comment]
![image](https://user-images.githubusercontent.com/8631079/28592265-72c0b1b0-7156-11e7-92a4-883cd0b0c89d.png)

**Comment by ccmorris** [comment]
Note: done in content
